spring:
  application:
    name: shorten-url-be
  datasource:
    url: jdbc:mysql://prod:3306/shorten-url?allowPublicKeyRetrieval=true&useSSL=false
    username: prod
    password: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

snowflake:
  data-center-id: 1
  worker-id: 1

server:
  error:
    whitelabel:
      enabled: false