spring:
  application:
    name: shorten-url-be
    server-url: https://shorten-url-be.viethq.tech
  datasource:
    url: jdbc:mysql://${QUALITY_DB_HOST}:3306/${QUALITY_DB}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${QUALITY_DB_USERNAME}
    password: ${QUALITY_DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

snowflake:
  data-center-id: 1
  worker-id: 1