name: SSH into VPS and deploy

on:
  push:
    branches:
      - quality

jobs:
  CD-job:
    runs-on: ubuntu-latest
    name: Deploy over SSH

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ..
          cd deployed-apps/shorten-url-be
          git pull origin quality
          git status
          docker rm -f shorten-url-be-app
          docker rmi shorten-url-be:quality
          docker build -t shorten-url-be:quality .
          docker run -it -d -e ENV=${{ secrets.ENV }} -e QUALITY_DB=${{ secrets.QUALITY_DB }} -e QUALITY_DB_USERNAME=${{ secrets.QUALITY_DB_USERNAME }} -e QUALITY_DB_PW=${{ secrets.QUALITY_DB_PW }} -e QUALITY_DB_HOST=${{ secrets.QUALITY_DB_HOST }}  -p 8080:8080 --name shorten-url-be-app shorten-url-be:quality
          
