name: SSH into VPS and deploy

on:
  push:
    branches:
      - quality

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy over SSH

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ..
          cd shorten-url-app/shorten-url-be
          git pull origin quality
          git status
          docker rm -f shorten-url-be-app
          docker build --secret ENV=${{ secrets.ENV }},QUALITY_DB=${{ secrets.QUALITY_DB }},QUALITY_DB_USERNAME=${{ secrets.QUALITY_DB_USERNAME }},QUALITY_DB_PW=${{ secrets.QUALITY_DB_PW }},QUALITY_DB_HOST=${{ secrets.QUALITY_DB_HOST }} -t shorten-url-be:quality .
          docker run -it -d -p 8080:8080 --name shorten-url-be-app shorten-url-be:quality
          
